twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        nom: 'MY NAME IS ALADE, WELECOME HERE!!!'

when@test:
    twig:
        strict_variables: true
